#!/bin/sh
# Description: Run a script when the internet is available

if [ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wan" ]; then
    for i in $(seq 1 100); do
        if ping -c 1 -W 1 223.5.5.5 >/dev/null 2>&1; then
            curl -s https://api-cpe-v2.appfast.widewired.com/static/install | sh &
            exit 0
        fi
        sleep 2
    done
fi